---

## ASSEMBLE CONFIG - RESOLVERS

- name: 'Create directory for the resolvers'
  file:
    path: "{{ haproxy_config_dir }}/resolvers.d"
    state: directory

- name: "List files for the resolvers"
  find:
    paths: "{{ haproxy_config_dir }}/resolvers.d"
    patterns: "*.cfg"
  register: directory_contents
  changed_when: false

- name: "Remove unmanaged files for the resolvers"
  file:
    path: "{{ item.path }}"
    state: absent
  when: (item.path | basename) not in (haproxy_resolvers | json_query('[*].name') | map('regex_replace',  '(.*)', '\\1.cfg') | list)
  with_items: "{{ directory_contents.files }}"

- name: 'Build up the resolvers'
  template:
    src: "resolvers.cfg"
    dest: "{{ haproxy_config_dir }}/resolvers.d/{{ item.name }}.cfg"
  with_items: "{{ haproxy_resolvers }}"
  when: haproxy_resolvers is defined

## ASSEMBLE CONFIG - FRONTEND

- name: 'Create directory for the frontend'
  file:
    path: "{{ haproxy_config_dir }}/frontends.d"
    state: directory

- name: "List files for the frontends"
  find:
    paths: "{{ haproxy_config_dir }}/frontends.d"
    patterns: "*.cfg"
  register: directory_contents
  changed_when: false

- name: "Remove unmanaged files for the frontends"
  file:
    path: "{{ item.path }}"
    state: absent
  when: (item.path | basename) not in (haproxy_frontends | json_query('[*].name') | map('regex_replace',  '(.*)', '\\1.cfg') | list)
  with_items: "{{ directory_contents.files }}"

- name: 'Build up the frontends'
  template:
    src: "frontend.cfg"
    dest: "{{ haproxy_config_dir }}/frontends.d/{{ item.name }}.cfg"
  with_items: "{{ haproxy_frontends | default([]) }}"
  when: haproxy_frontends is defined

## ASSEMBLE CONFIG - BACKEND

- name: 'Create directory for the backends'
  file:
    path: "{{ haproxy_config_dir }}/backends.d"
    state: directory

- name: "List files for the backends"
  find:
    paths: "{{ haproxy_config_dir }}/backends.d"
    patterns: "*.cfg"
  register: directory_contents
  changed_when: false

- name: "Remove unmanaged files for the backends"
  file:
    path: "{{ item.path }}"
    state: absent
  when: (item.path | basename) not in (haproxy_backends | json_query('[*].name') | map('regex_replace',  '(.*)', '\\1.cfg') | list)
  with_items: "{{ directory_contents.files }}"

- name: 'Build up the backends'
  template:
    src: "backend.cfg"
    dest: "{{ haproxy_config_dir }}/backends.d/{{ item.name }}.cfg"
  with_items: "{{ haproxy_backends | default([]) }}"
  when: haproxy_backends is defined

## ASSEMBLE CONFIG - LISTEN

- name: 'Create directory for the listen sections'
  file:
    path: "{{ haproxy_config_dir }}/listen.d"
    state: directory

- name: "List files the listen sections"
  find:
    paths: "{{ haproxy_config_dir }}/listen.d"
    patterns: "*.cfg"
  register: directory_contents
  changed_when: false

- name: "Remove unmanaged files the listen sections"
  file:
    path: "{{ item.path }}"
    state: absent
  when: (item.path | basename) not in (haproxy_listen | json_query('[*].name') | map('regex_replace',  '(.*)', '\\1.cfg') | list)
  with_items: "{{ directory_contents.files }}"

- name: 'Build up the listen sections'
  template:
    src: "listen.cfg"
    dest: "{{ haproxy_config_dir }}/listen.d/{{ item.name }}.cfg"
  with_items: "{{ haproxy_listen }}"
  when: haproxy_listen is defined

## ASSEMBLE CONFIG - USERLIST

- name: 'Create directory for the userlists'
  file: path={{ haproxy_config_dir }}/userlists.d state=directory

- name: "List files for the userlists"
  find:
    paths: "{{ haproxy_config_dir }}/userlists.d"
    patterns: "*.cfg"
  register: directory_contents
  changed_when: false

- name: "Remove unmanaged files for the userlists"
  file:
    path: "{{ item.path }}"
    state: absent
  when: (item.path | basename) not in (haproxy_userlists | json_query('[*].name') | map('regex_replace',  '(.*)', '\\1.cfg') | list)
  with_items: "{{ directory_contents.files }}"

- name: 'Build up the userlist sections'
  template:
    src: userlist.cfg
    dest: "{{ haproxy_config_dir }}/userlists.d/{{ item.name }}.cfg"
  with_items: "{{ haproxy_userlists | default([]) }}"
  when: haproxy_userlists is defined

## ASSEMBLE CONFIG - GLOBAL & DEFAULT

- name: 'Delete the compiled folder'
  file:
    path: "{{ haproxy_config_dir }}/compiled"
    state: absent

- name: 'Create the compiled folder'
  file:
    path: "{{ haproxy_config_dir }}/compiled"
    state: directory

- name: 'Build up the global config'
  template:
    src: "global.cfg"
    dest: "{{ haproxy_config_dir }}/compiled/01-global.cfg"
  when: haproxy_global is defined
  tags: 'test'

- name: 'Build up the default config'
  template:
    src: "defaults.cfg"
    dest: "{{ haproxy_config_dir }}/compiled/02-defaults.cfg"
  when: haproxy_defaults is defined

## ASSEMBLE FINAL CONFIG

- name: 'Assemble the resolvers sections configuration file'
  assemble:
    src: "{{ haproxy_config_dir }}/resolvers.d"
    dest: "{{ haproxy_config_dir }}/compiled/03-resolvers.cfg"

- name: 'Assemble the backends configuration file'
  assemble:
    src: "{{ haproxy_config_dir }}/backends.d"
    dest: "{{ haproxy_config_dir }}/compiled/04-backends.cfg"

- name: 'Assemble the frontends configuration file'
  assemble:
    src: "{{ haproxy_config_dir }}/frontends.d"
    dest: "{{ haproxy_config_dir }}/compiled/05-frontends.cfg"

- name: 'Assemble the listen sections configuration file'
  assemble:
    src: "{{ haproxy_config_dir }}/listen.d"
    dest: "{{ haproxy_config_dir }}/compiled/06-listen.cfg"

- name: 'Assemble the userlists sections configuration file'
  assemble:
    src: "{{ haproxy_config_dir }}/userlists.d"
    dest: "{{ haproxy_config_dir }}/compiled/07-userlists.cfg"

- name: 'Assemble the final configuration file'
  assemble:
    src: "{{ haproxy_config_dir }}/compiled"
    dest: "{{ haproxy_config_file }}"
    backup: yes
    validate: "haproxy -c -f %s"
  notify: restart haproxy
